{
 "title": "Overview",
 "description": "Node resources overview provided from Prometheus nodeExporter metrics",
 "tags": [
  "prometheus",
  "nodeExporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load1{job=~\"$job\"} * 100) by (hostname) / count (node_cpu_seconds_total{job=~\"$job\", mode=\"system\"}) by (hostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{device!~\"tmpfs|rootfs\", fstype=~\"ext4\"} / node_filesystem_size_bytes{device!~\"tmpfs|rootfs\", fstype=~\"ext4\"} * 100)",
     "legendFormat": "{{hostname}} - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~\"tmpfs|rootfs\", fstype=~\"ext4\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{hostname}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (hostname) (\n  node_hwmon_temp_celsius{chip=~\".*cpu.*|.*core.*\"} \n  or \n  node_thermal_zone_temp{type=~\".*cpu.*|.*thermal.*\"}\n  or\n  node_hwmon_temp_celsius{chip=~\"0000:00:03_1_0000:09:00_0\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "table",
   "description": "- *Load* - CPU capasity used (load average for last 1 minute divided by CPU cores count)\n- *CPU* - CPU usage\n- *Memory* - memory usage\n- *Filesystem* - filesystem usage\n- *Disk read* - maximum among all disks read rate\n- *Dist write* - maximum among all disks write rate\n- *Net recv* - maximum among all NIC's receive rate\n- *Net trans* - maximum among all NIC's transmit rate\n- *Net sock* - used network sockets \n- *TCP estab* - TCP established connections\n- *TCP tw* - TCP sockets in TIME-WAIT status",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"}"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$__rate_interval])) by (instance)) * 100"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"}))) * 100"
    },
    {
     "expr": "max((1 - (node_filesystem_free_bytes{job=~\"$job\"} / node_filesystem_size_bytes{job=~\"$job\"})) * 100) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$__rate_interval])) by (instance)"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[$__rate_interval])*8) by (instance)"
    },
    {
     "expr": "avg(node_load1{job=~\"$job\"} * 100) by (instance) / count (node_cpu_seconds_total{job=~\"$job\", mode=\"system\"}) by (instance)"
    },
    {
     "expr": "node_sockstat_sockets_used{job=~\"$job\"}"
    }
   ]
  }
 ]
}